### ISSUE TITLE
cmake can't find tbb on ubuntu 22.04

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace-restful#3]
i've installed libtbb-dev
```
$ dpkg -L libtbb-dev
...
/usr/include/oneapi/tbb/version.h
/usr/include/oneapi/tbb.h
/usr/include/tbb
/usr/include/tbb/blocked_range.h
/usr/include/tbb/blocked_range2d.h
...
```
but cmake can't find it:
```
$ cmake ..
...
-- Python destination dir found: /usr/local/lib/python3.10/dist-packages
-- Python install dir: /usr/local/lib/python3.10/dist-packages/opencog
-- Using nosetests executable /usr/bin/nosetests3
-- Looked for Threading Building Blocks in /opt/intel/tbb;/usr/local/include;/usr/include
-- Intel TBB (Threaded Building Blocks) was not found; the AtomSpace Publisher module will not be built. Installation instructions: https://www.threadingbuildingblocks.org/download
-- Found ZeroMQ library: /usr/lib/x86_64-linux-gnu/libzmq.so
-- Detected ZeroMQ version number: 4.3.4
-- ZeroMQ was found.
-- AttentionBank found.

Building for Ubuntu 22.04 LTS

The following components will be built:
-----------------------------------------------
   Doxygen       - Code documentation.
   Python tests  - Python bindings nose tests.
   Unit tests    - Unit tests.

The following components WILL NOT be built:
-----------------------------------------------
   REST Events   - REST Atomspace Event Publisher module.
```
any ideas about how to fix?

**Comment by linas** [comment]
The code in this repo will not work without a major overhaul. It has been non-functional for 6-8 years now.

**Comment by mjsduncan** [comment]
nil's temporal reasoning group has it working, i'll try to get them to push their fixes

**Comment by mjsduncan** [comment]
apparently it builds fine in ubuntu 20.04 with the caveats at the start of this file.  that doesn't help me with the cmake problem tho...
https://github.com/edyirdaw/rocca/blob/exp/examples/visualize_atoms/start_atomspace_restapi_server.py

**Comment by linas** [comment]
The CMakefile used to find TBB is here: https://github.com/opencog/cogutil/blob/master/cmake/FindTBB.cmake  -- you can either try to repair it, or try to find someone-else's version of this, from some other project on the interwebs, and use that. Create a pull req when you get a working version.

I'm pretty sure that this is the only opencog project that uses TBB so there's no risk of breaking anything else if you provide a different version.

**Comment by mjsduncan** [comment]
thanks, linus!

**Comment by mjsduncan** [comment]
i just set the location by hand in the CMakeLists.txt file:
```
# Threaded Building Blocks (Intel TBB) library
#FIND_PACKAGE(TBB)
#IF (TBB_FOUND)
   SET(HAVE_TBB 1)
   SET(TBB_INCLUDE_DIR "/usr/include/tbb")
#ELSE (TBB_FOUND)
SET(TBB_DIR_MESSAGE "tbb include directory is ${TBB_INCLUDE_DIR}")
#   SET(TBB_DIR_MESSAGE "Intel TBB (Threaded Building Blocks) was not found; th>
#ENDIF (TBB_FOUND)
MESSAGE(STATUS "${TBB_DIR_MESSAGE}")

```
